clc;
clear all;
close all;
x=input('enter the input sequence= ');
N=input('enter the value of N= ');
Xk=dftmtx(N)*x';
k=0:1:N-1;
subplot(2,1,1);
stem(k,abs(Xk));
xlabel('k');
ylabel('|x(k)|');
title('magnitude plot');
grid on;
subplot(2,1,2);
y=angle(Xk);
ang=rad2deg(y);
stem(k,ang);
xlabel('k');
ylabel('angle of x(k)');
title('phase plot');
grid on;
