clc;
clear all;
close all;
f=10;
fs=20*f;
t=0:1/fs:1;
a=2;
x=a*sin(2*pi*f*t);
subplot(3,2,1);
plot(t,x);
title('figure1 analog signal');
x1=x+2;
subplot(3,2,2);
plot(t,x1);
title('figure2 amplitude shifted signal');
subplot(3,2,3);
stem(t,x1);
title('figure3 sampled signal');
q=round(x1);
subplot(3,2,4);
stem(t,q);
title('figure4 quantised signal');

enco=de2bi(q,'left-msb');
subplot(3,2,5);
plot(t,enco);
title('figure5 encode signal');
deco=bi2de(enco,'left-msb');
deco=deco-2;
subplot(3,2,6);
plot(t,deco);
title('figure6 decoded signal');